### ISSUE TITLE
尝试运行项目时报错

### ISSUE THREAD

**Issue by EmptyDreams** [lqc520/uniapp-plugin#10]
报错内容如下：

```
Error: Vue3 项目暂不支持当前小程序
    at Object.getMPRuntimePath (D:\Programme\HBuilderX\plugins\uniapp-cli\node_modules\@dcloudio\uni-cli-shared\lib\platform.js:118:15)
    at Object.<anonymous> (D:\Programme\HBuilderX\plugins\uniapp-cli\node_modules\@dcloudio\webpack-uni-mp-loader\lib\plugin\generate-component.js:24:80)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\Programme\HBuilderX\plugins\uniapp-cli\node_modules\@dcloudio\webpack-uni-mp-loader\lib\plugin\index-new.js:17:27)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at createUniMPPlugin (D:\Programme\HBuilderX\plugins\uniapp-cli\node_modules\@dcloudio\vue-cli-plugin-uni\lib\mp\index.js:26:30)

进程已结束,退出代码1
```

我的启动配置：

![image](https://user-images.githubusercontent.com/44894906/236785005-8c3d6aa3-9fea-487c-930d-70285cb6198d.png)

启动配置调整为“发布”也会报错，请问是这个插件目前不支持 vue3 吗？还是我的配置有问题？

**Comment by lqc520** [comment]
是的 目前不支持vue3项目 因为我这边没有这个需求 后续版本会支持vue3

**Comment by EmptyDreams** [comment]
请问大概什么时候能够支持 vue3 呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jerry ***@***.***&gt;; 
发送时间: 2023年5月8日(星期一) 下午5:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lqc520/uniapp-plugin] 尝试运行项目时报错 (Issue #10)





 
是的 目前不支持vue3项目 因为我这边没有这个需求 后续版本会支持vue3

**Comment by lqc520** [comment]
[点我下载](https://github.com/lqc520/uniapp-plugin/releases/download/v1.0.4.A/Uniapp-1.0.4.zip)
