### ISSUE TITLE
最新版本的插件会影响正常vue项目vue.js插件的代码分析功能，右上角一直显示正在分析，影响代码高亮和语法

### ISSUE THREAD

**Issue by maomao124** [lqc520/uniapp-plugin#121]
今天上午打开项目发现idea打开vue文件一直处于正在分析状态，问题排查了很久，最后发现是插件问题

![image](https://github.com/user-attachments/assets/c73e4a45-cfb1-4530-aec1-f549ee090a7e)

![image](https://github.com/user-attachments/assets/bd12441a-6fc7-4a67-9e6f-5bef17f744d7)

![image](https://github.com/user-attachments/assets/20865cc3-3d29-49ed-9b09-ed4301ffaa78)

**Comment by lqc520** [comment]
如何复现
![image](https://github.com/user-attachments/assets/98e07c74-0847-41dd-94c3-fb908f5504b3)
 请a按照模板提问
![image](https://github.com/user-attachments/assets/265023af-5ea8-4bdf-8d80-994bfc3a056e)

**Comment by GavinAndre** [comment]
我也有这问题 打开ide会报错 然后一直卡分析 附上报错日志

`java.lang.IllegalArgumentException: Argument for @NotNull parameter 'patternOrMapping' of com/intellij/lang/javascript/frameworks/modules/JSPathMappingsUtil.isPatternOrMappingEndsWithStar must not be null
	at com.intellij.lang.javascript.frameworks.modules.JSPathMappingsUtil.$$$reportNull$$$0(JSPathMappingsUtil.java)
	at com.intellij.lang.javascript.frameworks.modules.JSPathMappingsUtil.isPatternOrMappingEndsWithStar(JSPathMappingsUtil.java)
	at com.intellij.lang.javascript.frameworks.modules.JSPathMappingsUtil.getMappings(JSPathMappingsUtil.java:194)
	at com.intellij.lang.javascript.frameworks.modules.JSPathMappingsUtil.getMappings(JSPathMappingsUtil.java:182)
	at com.intellij.lang.javascript.frameworks.modules.JSPathMappingsUtil.substituteMappings(JSPathMappingsUtil.java:55)
	at com.intellij.lang.javascript.frameworks.modules.resolver.JSFileImportsResolverImpl$resolveFromPathMappings$1.invoke(JSFileImportsResolverImpl.kt:386)
	at com.intellij.lang.javascript.frameworks.modules.resolver.JSFileImportsResolverImpl$resolveFromPathMappings$1.invoke(JSFileImportsResolverImpl.kt:384)
	at com.intellij.lang.javascript.frameworks.modules.resolver.JSFileImportsResolverImpl.computeWithCache(JSFileImportsResolverImpl.kt:531)
	at com.intellij.lang.javascript.frameworks.modules.resolver.JSFileImportsResolverImpl.resolveFromPathMappings(JSFileImportsResolverImpl.kt:384)
	at com.intellij.lang.javascript.frameworks.modules.resolver.JSFileImportsResolverImpl.resolveModuleWithElements(JSFileImportsResolverImpl.kt:107)
	at com.intellij.lang.javascript.frameworks.modules.resolver.JSFileImportsResolverImpl.resolveDirectFile(JSFileImportsResolverImpl.kt:83)
	at com.intellij.lang.javascript.frameworks.modules.resolver.JSDefaultFileReferenceAltResolver.calculateForJavaScript(JSDefaultFileReferenceAltResolver.java:107)
	at com.intellij.lang.javascript.frameworks.modules.resolver.JSDefaultFileReferenceAltResolver.altResolve(JSDefaultFileReferenceAltResolver.java:78)
	at com.intellij.lang.javascript.frameworks.modules.resolver.JSDefaultFileReferenceAltResolver.lambda$altResolveWithCache$0(JSDefaultFileReferenceAltResolver.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.kt:40)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:236)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:236)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:237)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.kt:34)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:83)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:126)
	at com.intellij.lang.javascript.frameworks.modules.resolver.JSDefaultFileReferenceAltResolver.altResolveWithCache(JSDefaultFileReferenceAltResolver.java:59)
	at com.intellij.lang.javascript.frameworks.modules.JSFileModuleReference.innerResolve(JSFileModuleReference.java:91)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference$MyResolver.resolve(FileReference.java:590)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference$MyResolver.resolve(FileReference.java:585)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$2(ResolveCache.java:182)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:242)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:221)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:182)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference.multiResolve(FileReference.java:117)
	at com.intellij.lang.javascript.psi.resolve.JSModuleReferenceContributor.resolveModuleReference(JSModuleReferenceContributor.java:216)
	at com.intellij.lang.javascript.psi.resolve.JSModuleReferenceContributor.resolveReferences(JSModuleReferenceContributor.java:108)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferencesUtil.processContributor(JSFileReferencesUtil.java:239)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferencesUtil.getMostPriorityModules(JSFileReferencesUtil.java:199)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferencesUtil.calculateMainModules(JSFileReferencesUtil.java:135)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferenceCache.lambda$static$0(JSFileReferenceCache.java:40)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferenceCache.lambda$createModulesCachedValueForText$4(JSFileReferenceCache.java:139)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.kt:40)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:236)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:236)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:237)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.kt:34)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferenceCache.getCachedModules(JSFileReferenceCache.java:130)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferenceCache.resolveModules(JSFileReferenceCache.java:91)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferenceCache.resolveModuleReference(JSFileReferenceCache.java:70)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferenceCache.resolveModuleReferences(JSFileReferenceCache.java:64)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferencesUtil.resolveModuleReferences(JSFileReferencesUtil.java:86)
	at com.intellij.lang.ecmascript6.resolve.JSFileReferencesUtil.resolveModuleReferences(JSFileReferencesUtil.java:82)
	at com.intellij.lang.ecmascript6.psi.impl.ES6FromClauseImpl.resolveReferencedElements(ES6FromClauseImpl.java:67)
	at com.intellij.lang.ecmascript6.resolve.ES6PsiUtil.getFromClauseResolvedReferences(ES6PsiUtil.java:194)
	at com.intellij.lang.ecmascript6.resolve.ES6PsiUtil.resolveSymbolForSpecifier(ES6PsiUtil.java:339)
	at com.intellij.lang.javascript.psi.util.JSStubBasedPsiTreeUtil.calculateMeaningfulElements(JSStubBasedPsiTreeUtil.java:672)
	at com.intellij.lang.javascript.psi.util.JSStubBasedPsiTreeUtil.calculateMeaningfulElements(JSStubBasedPsiTreeUtil.java:715)
	at com.intellij.lang.javascript.psi.util.JSStubBasedPsiTreeUtil.calculateMeaningfulElements(JSStubBasedPsiTreeUtil.java:539)
	at org.jetbrains.vuejs.model.source.VueComponents$Companion.meaningfulExpression(VueComponents.kt:48)
	at org.jetbrains.vuejs.model.source.VueDefaultContainerInfoProvider$ComponentsAccessor$build$3.invoke(VueDefaultContainerInfoProvider.kt:159)
	at org.jetbrains.vuejs.model.source.VueDefaultContainerInfoProvider$ComponentsAccessor$build$3.invoke(VueDefaultContainerInfoProvider.kt:158)
	at org.jetbrains.vuejs.model.source.VueDefaultContainerInfoProvider$ComponentsAccessor.build$lambda$2(VueDefaultContainerInfoProvider.kt:158)
	at one.util.streamex.EntryStream.lambda$mapValues$13(EntryStream.java:516)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
	at one.util.streamex.EntryStream.into(EntryStream.java:1553)
	at org.jetbrains.vuejs.model.source.VueDefaultContainerInfoProvider$ComponentsAccessor.build(VueDefaultContainerInfoProvider.kt:182)
	at org.jetbrains.vuejs.model.source.VueDefaultContainerInfoProvider$ComponentsAccessor.build(VueDefaultContainerInfoProvider.kt:154)
	at org.jetbrains.vuejs.model.source.EntityContainerInfoProvider$InitializedContainerInfoProvider$InitializedContainerInfo.get(EntityContainerInfoProvider.kt:65)
	at org.jetbrains.vuejs.model.source.VueDefaultContainerInfoProvider$VueSourceContainerInfo.getComponents(VueDefaultContainerInfoProvider.kt:46)
	at org.jetbrains.vuejs.model.source.VueSourceContainer$Companion$COMPONENTS$1.get(VueSourceContainer.kt:70)
	at kotlin.jvm.internal.PropertyReference1.invoke(PropertyReference1.java:35)
	at org.jetbrains.vuejs.model.source.VueSourceContainer$MemberAccessor$get$1.invoke(VueSourceContainer.kt:99)
	at org.jetbrains.vuejs.model.source.VueSourceContainer$MemberAccessor$get$1.invoke(VueSourceContainer.kt:97)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at org.jetbrains.vuejs.model.source.VueSourceContainer$MemberAccessor.get(VueSourceContainer.kt:196)
	at org.jetbrains.vuejs.model.source.VueSourceContainer.get(VueSourceContainer.kt:49)
	at org.jetbrains.vuejs.model.source.VueSourceContainer.getComponents(VueSourceContainer.kt:41)
	at org.jetbrains.vuejs.model.VueScopeElement.acceptEntities(VueScopeElement.kt:68)
	at org.jetbrains.vuejs.web.scopes.VueCodeModelSymbolsScope.visitContainer(VueCodeModelSymbolsScope.kt:98)
	at org.jetbrains.vuejs.web.scopes.VueCodeModelSymbolsScope.initialize(VueCodeModelSymbolsScope.kt:87)
	at com.intellij.webSymbols.WebSymbolsScopeWithCache.createCachedSearchMap$lambda$3(WebSymbolsScopeWithCache.kt:102)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.kt:40)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:236)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:236)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:237)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.kt:34)
	at com.intellij.webSymbols.WebSymbolsScopeWithCache$NamesProviderToMapCache.getOrCreateMap(WebSymbolsScopeWithCache.kt:163)
	at com.intellij.webSymbols.WebSymbolsScopeWithCache.getMap(WebSymbolsScopeWithCache.kt:147)
	at com.intellij.webSymbols.WebSymbolsScopeWithCache.getMatchingSymbols(WebSymbolsScopeWithCache.kt:122)
	at org.jetbrains.vuejs.web.scopes.VueIncorrectlySelfReferredComponentFilteringScope.getMatchingSymbols(VueIncorrectlySelfReferredComponentFilteringScope.kt:28)
	at com.intellij.webSymbols.query.impl.WebSymbolsQueryExecutorImpl$runNameMatchQuery$1$result$1.invoke(WebSymbolsQueryExecutorImpl.kt:136)
	at com.intellij.webSymbols.query.impl.WebSymbolsQueryExecutorImpl$runNameMatchQuery$1$result$1.invoke(WebSymbolsQueryExecutorImpl.kt:134)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.DistinctIterator.computeNext(Sequences.kt:570)
	at kotlin.collections.AbstractIterator.tryToComputeNext(AbstractIterator.kt:42)
	at kotlin.collections.AbstractIterator.hasNext(AbstractIterator.kt:29)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:809)
	at com.intellij.webSymbols.query.impl.WebSymbolsQueryExecutorImpl$runNameMatchQuery$1.invoke(WebSymbolsQueryExecutorImpl.kt:140)
	at com.intellij.webSymbols.query.impl.WebSymbolsQueryExecutorImpl$runNameMatchQuery$1.invoke(WebSymbolsQueryExecutorImpl.kt:128)
	at com.intellij.webSymbols.query.impl.WebSymbolsQueryExecutorImpl.runQuery$lambda$13(WebSymbolsQueryExecutorImpl.kt:267)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.webSymbols.query.impl.WebSymbolsQueryExecutorImpl.runQuery(WebSymbolsQueryExecutorImpl.kt:251)
	at com.intellij.webSymbols.query.impl.WebSymbolsQueryExecutorImpl.runNameMatchQuery(WebSymbolsQueryExecutorImpl.kt:128)
	at com.intellij.webSymbols.query.impl.WebSymbolsQueryExecutorImpl.runNameMatchQuery(WebSymbolsQueryExecutorImpl.kt:68)
	at com.intellij.webSymbols.webTypes.json.WebTypesJsonUtilsKt$resolve$1.invoke(WebTypesJsonUtils.kt:193)
	at com.intellij.webSymbols.webTypes.json.WebTypesJsonUtilsKt$resolve$1.invoke(WebTypesJsonUtils.kt:192)
	at com.intellij.webSymbols.webTypes.json.WebTypesJsonUtilsKt.processWebSymbols(WebTypesJsonUtils.kt:232)
	at com.intellij.webSymbols.webTypes.json.WebTypesJsonUtilsKt.resolve(WebTypesJsonUtils.kt:192)
	at com.intellij.webSymbols.webTypes.json.WebTypesJsonUtilsKt.resolve$default(WebTypesJsonUtils.kt:187)
	at com.intellij.webSymbols.webTypes.impl.WebTypesComplexPatternConfigProvider$PatternSymbolsResolver.matchName(WebTypesPatternUtils.kt:186)
	at com.intellij.webSymbols.patterns.impl.SymbolReferencePattern.match$intellij_platform_webSymbols(SymbolReferencePattern.kt:43)
	at com.intellij.webSymbols.patterns.impl.SequencePattern$match$1.invoke(SequencePattern.kt:43)
	at com.intellij.webSymbols.patterns.impl.SequencePattern$match$1.invoke(SequencePattern.kt:41)
	at com.intellij.webSymbols.patterns.impl.SequencePattern.process(SequencePattern.kt:420)
	at com.intellij.webSymbols.patterns.impl.SequencePattern.match$intellij_platform_webSymbols(SequencePattern.kt:41)
	at com.intellij.webSymbols.patterns.impl.ComplexPattern.performPatternMatch(ComplexPattern.kt:236)
	at com.intellij.webSymbols.patterns.impl.ComplexPattern.access$performPatternMatch(ComplexPattern.kt:27)
	at com.intellij.webSymbols.patterns.impl.ComplexPattern$match$1.invoke(ComplexPattern.kt:48)
	at com.intellij.webSymbols.patterns.impl.ComplexPattern$match$1.invoke(ComplexPattern.kt:46)
	at com.intellij.webSymbols.patterns.impl.ComplexPattern.process(ComplexPattern.kt:168)
	at com.intellij.webSymbols.patterns.impl.ComplexPattern.match$intellij_platform_webSymbols(ComplexPattern.kt:46)
	at com.intellij.webSymbols.patterns.WebSymbolsPattern.match$intellij_platform_webSymbols(WebSymbolsPattern.kt:25)
	at com.intellij.webSymbols.utils.WebSymbolUtils.match(WebSymbolUtils.kt:128)
	at com.intellij.webSymbols.query.impl.SearchMap$collectPatternContributions$1.invoke(SearchMap.kt:105)
	at com.intellij.webSymbols.query.impl.SearchMap$collectPatternContributions$1.invoke(SearchMap.kt:104)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:809)
	at com.intellij.webSymbols.query.impl.SearchMap.collectPatternContributions(SearchMap.kt:107)
	at com.intellij.webSymbols.query.impl.SearchMap.getMatchingSymbols$intellij_platform_webSymbols(SearchMap.kt:57)
	at com.intellij.webSymbols.impl.StaticWebSymbolsScopeBase$getMatchingSymbols$1.invoke(StaticWebSymbolsScopeBase.kt:40)
	at com.intellij.webSymbols.impl.StaticWebSymbolsScopeBase$getMatchingSymbols$1.invoke(StaticWebSymbolsScopeBase.kt:39)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:809)
	at com.intellij.webSymbols.impl.StaticWebSymbolsScopeBase.getMatchingSymbols(StaticWebSymbolsScopeBase.kt:41)
	at com.intellij.javascript.webSymbols.nodejs.PackageJsonWebSymbolsScopeImpl.getMatchingSymbols(PackageJsonWebSymbolsScopeImpl.kt:55)
	at com.intellij.webSymbols.query.impl.WebSymbolsQueryExecutorImpl$runNameMatchQuery$1$result$1.invoke(WebSymbolsQueryExecutorImpl.kt:136)
	at com.intellij.webSymbols.query.impl.WebSymbolsQueryExecutorImpl$runNameMatchQuery$1$result$1.invoke(WebSymbolsQueryExecutorImpl.kt:134)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.DistinctIterator.computeNext(Sequences.kt:570)
	at kotlin.collections.AbstractIterator.tryToComputeNext(AbstractIterator.kt:42)
	at kotlin.collections.AbstractIterator.hasNext(AbstractIterator.kt:29)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:809)
	at com.intellij.webSymbols.query.impl.WebSymbolsQueryExecutorImpl$runNameMatchQuery$1.invoke(WebSymbolsQueryExecutorImpl.kt:140)
	at com.intellij.webSymbols.query.impl.WebSymbolsQueryExecutorImpl$runNameMatchQuery$1.invoke(WebSymbolsQueryExecutorImpl.kt:128)
	at com.intellij.webSymbols.query.impl.WebSymbolsQueryExecutorImpl.runQuery$lambda$13(WebSymbolsQueryExecutorImpl.kt:267)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.webSymbols.query.impl.WebSymbolsQueryExecutorImpl.runQuery(WebSymbolsQueryExecutorImpl.kt:251)
	at com.intellij.webSymbols.query.impl.WebSymbolsQueryExecutorImpl.runNameMatchQuery(WebSymbolsQueryExecutorImpl.kt:128)
	at com.intellij.webSymbols.query.impl.WebSymbolsQueryExecutorImpl.runNameMatchQuery(WebSymbolsQueryExecutorImpl.kt:68)
	at com.intellij.webSymbols.query.WebSymbolsQueryExecutor.runNameMatchQuery(WebSymbolsQueryExecutor.kt:43)
	at com.intellij.webSymbols.query.WebSymbolsQueryExecutor.runNameMatchQuery$default(WebSymbolsQueryExecutor.kt:36)
	at com.intellij.html.webSymbols.elements.WebSymbolElementDescriptorsProvider.getDescriptor(WebSymbolElementDescriptorsProvider.kt:24)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.computeElementDescriptor(XmlTagDelegate.java:455)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate$1.compute(XmlTagDelegate.java:436)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:173)
	at com.intellij.psi.impl.PsiCachedValueImpl$Direct.doCompute(PsiCachedValueImpl.kt:77)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:236)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:236)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:237)
	at com.intellij.psi.impl.PsiCachedValueImpl$Direct.getValue(PsiCachedValueImpl.kt:81)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:83)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:170)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:136)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getDescriptor(XmlTagDelegate.java:432)
	at com.intellij.psi.impl.source.xml.XmlStubBasedTagBase.getDescriptor(XmlStubBasedTagBase.java:130)
	at com.intellij.xml.XmlCustomTagHighlightingPass$doCollectInformation$1.visitXmlTag(XmlCustomTagHighlightingPass.kt:49)
	at com.intellij.psi.impl.source.xml.XmlStubBasedTagBase.accept(XmlStubBasedTagBase.java:278)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:58)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:11)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:63)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:40)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:67)
	at com.intellij.psi.XmlRecursiveElementWalkingVisitor.visitElement(XmlRecursiveElementWalkingVisitor.java:40)
	at com.intellij.psi.XmlElementVisitor.visitXmlElement(XmlElementVisitor.java:23)
	at com.intellij.psi.XmlElementVisitor.visitXmlDocument(XmlElementVisitor.java:43)
	at com.intellij.psi.impl.source.xml.XmlDocumentImpl.accept(XmlDocumentImpl.java:52)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:183)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:832)
	at com.intellij.xml.XmlCustomTagHighlightingPass.doCollectInformation(XmlCustomTagHighlightingPass.kt:46)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:418)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:118)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:36)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:413)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$4(PassExecutorService.java:404)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:403)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:379)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:802)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$1(PassExecutorService.java:379)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:377)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:190)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
`

**Comment by 320187240** [comment]
我也有同样的问题 idea版本 2024.1.6 (Ultimate Edition)  安装 vue.js 与uniapp-tool ，禁用 uniapp-tool并重启idea后可恢复语法分析功能。

**Comment by gp0119** [comment]
+1
搜索[youtrack](https://youtrack.jetbrains.com/issue/WEB-69647/java.lang.IllegalArgumentException-Argument-for-NotNull-parameter-patternOrMapping-of)发现是插件问题

**Comment by lqc520** [comment]
无法复现 因为你们没有提供复现环境 请安装模板提问

**Comment by lqc520** [comment]
uniapp 1.0.16-241.2 IntelliJ IDEA 2024.2.2 (Ultimate Edition) vue vite ts 项目正常

**Comment by gp0119** [comment]
有几个公司的项目会这样，是 vue2+webpack 的项目，但我用 vue cli 新建一个vue2项目又复现不出来，不知道到底是什么影响的

**Comment by gp0119** [comment]
@lqc520 github找到了一个项目会出现这种情况 [vue2-manage](https://github.com/bailicangdu/vue2-manage)

**Comment by lqc520** [comment]
@gp0119 已复现 感谢反馈
