### ISSUE TITLE
webstorm 2023.2.2 等待更新了两个版本的插件都报错

### ISSUE THREAD

**Issue by TopFiveGao** [lqc520/uniapp-plugin#68]
**描述错误**
对bug的简明描述.

还请添加显示问题的屏幕截图.

**使用的插件版本**
Uniapp Tool:1.0.9 
vue: 2/3 
project: cli-js/cli-ts/hbx
ide: WebStorm 2023.2.2 

**环境**
提供更多的信息:
比如:  win11
(欢迎其他信息帮助我们调试)

**如何重现**
重现行为的步骤:
1. 之前用 webstorm 安装 uniapp tool 是正常的；
2. 某一天推送 uniapp-tool 插件更新了，于是就更新；
3. 更新后就报错，无法使用插件，
4. 只好 disabled uniapp-tool；
5. 又一天再次推送 uniapp-tool 插件更新了，想着也许作者发现并解决了这个更新后无法使用插件的问题，于是再次更新；
6. 结果新版本还是不能使用；
7. 作为一名用户，本身就是在享受作者开源的插件，但这两次更新都有问题，所以友善提一个issue.
8. 报错简略信息如下：
```java
Caused by: java.lang.ClassNotFoundException: cn.fjdmy.uniapp.lang.json.UniappJsonSchemaProviderFactory PluginClassLoader(plugin=PluginDescriptor(name=Uniapp Tool, id=cn.fjdmy.uniapp, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\WebStorm2023.2\plugins\Uniapp, version=1.0.8-231.5, package=null, isBundled=false), packagePrefix=null, state=active)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1607)
	at com.intellij.serviceContainer.ComponentManagerImplKt.access$doLoadClass(ComponentManagerImpl.kt:1)
	at com.intellij.serviceContainer.ComponentManagerImpl.loadClass(ComponentManagerImpl.kt:947)
	at com.intellij.openapi.extensions.impl.InterfaceExtensionImplementationClassResolver.resolveImplementationClass(InterfaceExtensionImplementationClassResolver.kt:24)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:48)
```

**预期行为**
新版本插件安装后可以正常使用。

**Comment by lqc520** [comment]
带图 
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/ccf393db-f312-4f95-a0aa-cb3cd249b463)
我这边使用没有这个报错
