### ISSUE TITLE
新建页面与已有页面路径重复时会报错

### ISSUE THREAD

**Issue by nullnan** [lqc520/uniapp-plugin#79]
**描述错误**
java.lang.RuntimeException: com.intellij.util.IncorrectOperationException: File '/path/to/xxxx' already exists.
	at cn.fjdmy.uniapp.action.J.ALLATORIxDEMO(oc:159)
	at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$4(WriteCommandAction.java:360)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$1(WriteCommandAction.java:149)
省略
还请添加显示问题的屏幕截图.

**使用的插件版本**
Uniapp Tool: x.x.x 
vue: 2/3 
project: cli-js/cli-ts/hbx
ide: WebStorm 202x.x.x 

**环境**
提供更多的信息:
比如:  win11/macOS
(欢迎其他信息帮助我们调试)

**如何重现**
重现行为的步骤:
1. 点击新建页面
2. 输入已经存在/pages/下的页面路径

**预期行为**
填写路径出现重复时最好能弹窗提示一下就好了。

**Comment by lqc520** [comment]
后续版本做个提示
