### ISSUE TITLE
WebStorm 2023.2.5  中插件报错

### ISSUE THREAD

**Issue by lxhtiamo** [lqc520/uniapp-plugin#85]
![image](https://github.com/lqc520/uniapp-plugin/assets/22663888/15edd5de-ea27-4f20-ad6f-461ffdb3a2e0)

java.lang.IllegalArgumentException: Must pass FS root path, but got: 'F:///', which has a parent 'F:'. Use NewVirtualFileSystem.extractRootPath() for obtaining root path
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findRoot(PersistentFSImpl.java:1495)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.cacheRootsByUrls(PersistentFSImpl.java:1620)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.cacheSingleMissedRootFromPersistence(PersistentFSImpl.java:1602)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl$ParentFinder.ascendUntilCachedParent(PersistentFSImpl.java:1685)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl$ParentFinder.find(PersistentFSImpl.java:1806)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findFileById(PersistentFSImpl.java:1567)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findFileById(PersistentFSImpl.java:64)
	at com.intellij.util.indexing.FileBasedIndexScanUtil.processFilesContainingAnyKey(FileBasedIndexScanUtil.java:249)
	at com.intellij.util.indexing.FileBasedIndexImpl.processFilesContainingAnyKey(FileBasedIndexImpl.java:1168)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByNames(FilenameIndex.java:214)
	at com.intellij.psi.search.FilenameIndex.getAllFilesByExt(FilenameIndex.java:207)
	at com.intellij.psi.search.FilenameIndex.getAllFilesByExt(FilenameIndex.java:190)
	at cn.fjdmy.uniapp.lang.vue.EasycomVueContainerInfoProvider.ALLATORIxDEMO(ba:193)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:895)
	at cn.fjdmy.uniapp.lang.vue.EasycomVueContainerInfoProvider.M(ba:79)
	at cn.fjdmy.uniapp.lang.vue.EasycomVueContainerInfoProvider.ALLATORIxDEMO(ba:14)
	at cn.fjdmy.uniapp.lang.vue.EasycomVueContainerInfoProvider.getAdditionalComponents(ba:195)
	at org.jetbrains.vuejs.model.source.VueSourceGlobal$getComponents$1.invoke(VueSourceGlobal.kt:115)
	at org.jetbrains.vuejs.model.source.VueSourceGlobal$getComponents$1.invoke(VueSourceGlobal.kt:71)
	at org.jetbrains.vuejs.model.source.VueSourceGlobal.getCachedValue$lambda$4(VueSourceGlobal.kt:147)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:110)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:65)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:69)
	at org.jetbrains.vuejs.model.source.VueSourceGlobal.getCachedValue(VueSourceGlobal.kt:142)
	at org.jetbrains.vuejs.model.source.VueSourceGlobal.getComponents(VueSourceGlobal.kt:71)
	at org.jetbrains.vuejs.model.source.VueSourceGlobal.getComponents(VueSourceGlobal.kt:45)
	at org.jetbrains.vuejs.model.VueDelegatedEntitiesContainer.getComponents(VueDelegatedEntitiesContainer.kt:10)
	at org.jetbrains.vuejs.model.VueGlobalImpl.buildElementToParentMap(VueGlobalImpl.kt:81)
	at org.jetbrains.vuejs.model.VueGlobalImpl.getElementToParentMap$lambda$0(VueGlobalImpl.kt:49)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:110)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:65)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:69)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:111)
	at org.jetbrains.vuejs.model.VueGlobalImpl.getElementToParentMap(VueGlobalImpl.kt:48)
	at org.jetbrains.vuejs.model.VueGlobalImpl.getParents(VueGlobalImpl.kt:45)
	at org.jetbrains.vuejs.model.typed.VueTypedGlobal.getParents(VueTypedGlobal.kt:47)
	at org.jetbrains.vuejs.model.VueGlobalImpl$Companion.getParents(VueGlobalImpl.kt:121)
	at org.jetbrains.vuejs.model.source.VueSourceContainer.getParents(VueSourceContainer.kt:19)
	at org.jetbrains.vuejs.web.VueWebSymbolsQueryConfigurator.addEntityContainers(VueWebSymbolsQueryConfigurator.kt:145)
	at org.jetbrains.vuejs.web.VueWebSymbolsQueryConfigurator.getScope(VueWebSymbolsQueryConfigurator.kt:70)
	at com.intellij.webSymbols.query.impl.WebSymbolsQueryExecutorFactoryImpl.create(WebSymbolsQueryExecutorFactoryImpl.kt:44)
	at com.intellij.webSymbols.query.WebSymbolsQueryExecutorFactory$Companion.create(WebSymbolsQueryExecutorFactory.kt:28)
	at com.intellij.webSymbols.query.WebSymbolsQueryExecutorFactory$Companion.create$default(WebSymbolsQueryExecutorFactory.kt:27)
	at com.intellij.html.webSymbols.elements.WebSymbolElementDescriptorsProvider.getDescriptor(WebSymbolElementDescriptorsProvider.kt:22)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.computeElementDescriptor(XmlTagDelegate.java:465)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:110)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:65)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate$1.compute(XmlTagDelegate.java:444)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:110)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:65)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:69)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getDescriptor(XmlTagDelegate.java:440)
	at com.intellij.psi.impl.source.xml.XmlStubBasedTagBase.getDescriptor(XmlStubBasedTagBase.java:130)
	at com.intellij.html.webSymbols.elements.WebSymbolInTagNameRefProvider.getSymbol(WebSymbolInTagNameRefProvider.kt:13)
	at com.intellij.html.webSymbols.elements.WebSymbolInTagNameRefProvider.getOffsetsToSymbols(WebSymbolInTagNameRefProvider.kt:18)
	at com.intellij.html.webSymbols.elements.WebSymbolInTagNameRefProvider.getOffsetsToSymbols(WebSymbolInTagNameRefProvider.kt:10)
	at com.intellij.webSymbols.references.WebSymbolReferenceProvider.getReferences(WebSymbolReferenceProvider.kt:70)
	at com.intellij.webSymbols.references.WebSymbolReferenceProvider.getReferences$lambda$0(WebSymbolReferenceProvider.kt:43)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:110)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:65)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:69)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.webSymbols.references.WebSymbolReferenceProvider.getReferences(WebSymbolReferenceProvider.kt:41)
	at com.intellij.model.psi.impl.PsiSymbolReferenceServiceImpl.lambda$doGetExternalReferences$1(PsiSymbolReferenceServiceImpl.java:74)
	at com.intellij.model.psi.impl.PsiSymbolReferenceServiceImpl.doGetExternalReferences(PsiSymbolReferenceServiceImpl.java:86)
	at com.intellij.model.psi.impl.PsiSymbolReferenceServiceImpl.getReferences(PsiSymbolReferenceServiceImpl.java:44)
	at com.intellij.model.psi.impl.PsiSymbolReferenceServiceImpl.getReferences(PsiSymbolReferenceServiceImpl.java:20)
	at com.intellij.model.psi.impl.ReferencesKt.referencesInElement(references.kt:76)
	at com.intellij.model.psi.impl.ReferencesKt.allReferencesInElement(references.kt:59)
	at com.intellij.model.psi.impl.ReferencesKt.allReferencesAround(references.kt:36)
	at com.intellij.model.psi.impl.TargetsKt.declarationsOrReferences(targets.kt:134)
	at com.intellij.model.psi.impl.TargetsKt.declaredReferencedData(targets.kt:42)
	at com.intellij.model.psi.impl.TargetsKt.targetSymbols(targets.kt:24)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getTargetSymbols(IdentifierHighlighterPass.java:216)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.highlightReferencesAndDeclarations(IdentifierHighlighterPass.java:208)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:97)
	at com.intellij.codeInsight.highlighting.BackgroundHighlighter.lambda$submitIdentifierHighlighterPass$5(BackgroundHighlighter.java:219)
	at com.intellij.codeInsight.daemon.impl.HighlightingSessionImpl.runInsideHighlightingSession(HighlightingSessionImpl.java:157)
	at com.intellij.codeInsight.highlighting.BackgroundHighlighter.lambda$submitIdentifierHighlighterPass$6(BackgroundHighlighter.java:217)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:133)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:114)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:111)
	at com.intellij.codeInsight.highlighting.BackgroundHighlighter.lambda$submitIdentifierHighlighterPass$7(BackgroundHighlighter.java:214)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:832)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:864)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:602)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$4(NonBlockingReadActionImpl.java:565)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:133)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:114)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:111)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:565)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:466)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$2(NonBlockingReadActionImpl.java:481)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

**描述错误**
对bug的简明描述.

还请添加显示问题的屏幕截图.

**使用的插件版本**
Uniapp Tool: x.x.x 
vue: 2/3 
project: cli-js/cli-ts/hbx
ide: WebStorm 202x.x.x 

**环境**
提供更多的信息:
比如:  win11/macOS
(欢迎其他信息帮助我们调试)

**如何重现**
重现行为的步骤:

**预期行为**
对你期望发生的事情进行清晰简洁的描述.

**Comment by lqc520** [comment]
去下载最新版本看看
