### ISSUE TITLE
RuntimeExceptionWithAttachments: Read access is allowed from inside read-action

### ISSUE THREAD

**Issue by xiaohe0601** [lqc520/uniapp-plugin#99]
**描述错误**
```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details
Current thread: Thread[DefaultDispatcher-worker-65,5,main] 212122939 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1555746150
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:149)
	at com.intellij.util.concurrency.ThreadingAssertions.softAssertReadAccess(ThreadingAssertions.java:107)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1012)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:162)
	at cn.fjdmy.uniapp.listener.UniappProjectActivity.ALLATORIxDEMO(oa:40)
	at cn.fjdmy.uniapp.listener.UniappProjectActivity.ALLATORIxDEMO(oa:25)
	at cn.fjdmy.uniapp.listener.UniappProjectActivity.H(oa:437)
	at cn.fjdmy.uniapp.listener.UniappProjectActivity.execute(oa:375)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1.invokeSuspend(StartupManagerImpl.kt:482)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**使用的插件版本**
Uniapp Tool: 1.0.13-231.1
vue: 3 
project: cli-ts
ide: WebStorm 2023.3.4

**Comment by lqc520** [comment]
感谢反馈 先回退到上个版本哈

**Comment by lqc520** [comment]
你试试
[Uniapp.zip](https://github.com/lqc520/uniapp-plugin/files/14435210/Uniapp.zip)

**Comment by xiaohe0601** [comment]
没问题了，感谢！
